routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// prefix is for route and namespace is for controllers directory
// for guest room
Route::group(['namespace' => 'Guest'], function () {
    Route::resource('cpdGuest', 'RoomDashboardController');
    Route::resource('cpdGuestRoom', 'RoomController');
});
// for login 
Route::get('/', function () {
    return view('auth.login');
});

// for files download
Route::resource('files_download', 'FilesDownloadController');
// for main dashboard
Route::resource('main_dashboard', 'MainDashboardController');


///////////////////// FOR MEMBERS ROUTES //////////////////////////////// 
Route::group(['prefix' => 'Member','namespace' => 'Member'], function () {
    
    // for video conference
    Route::group(['namespace' => 'Conference'], function () {
        Route::resources([
            'conference_dashboard'=>'ConferenceDashboardController',
            'conference_room'=>'ConferenceRoomController',
        ]);
    });
    // for library
    Route::resources([
        'library_dashboard'=>'LibraryController',
        
    ]);
    // for messages
    Route::resources([
        'message_dashboard'=>'MessageController',
        
    ]);
});
// for trainees
Route::group(['prefix' => 'Trainee','namespace' => 'Trainee'], function () {
    Route::resources([
        'dashboard'=>'DashboardController',
        'course_materials'=>'CourseMatController',
        'registration'=>'RegistrationController',
        'fees'=>'FeeController',
        'lecturer_assessment'=>'LecturerAssessController',
        'trainee_conference'=>'ConferenceController',
        'results'=>'ResultController',
        'profile'=>'ProfileController',
    ]);

});

//////////////////////////////////////// FOR ADMIN ////////////////////////////
Route::group(['prefix' => 'Admin','namespace' => 'Admin'], function () {
    // for Members
    Route::group(['namespace' => 'Member'], function () {
        Route::resources([
            'member_dashboard'=>'DashboardController',
            'member_manage'=>'ManageController',
            'member_type'=>'MemberTypeController',
            'member_designation'=>'MemberDesignationController',
            'member_report'=>'ReportController',
            
        ]);
    });
    // for division
    Route::group(['namespace' => 'Division'], function () {
        Route::resources([
            'division_dashboard'=>'DashboardController',
            'division_manage'=>'ManageController',
            'division_account'=>'AccountController',
            'division_report'=>'ReportsController',
            
        ]);
    });
    // for users
    Route::group(['namespace' => 'Users'], function () {
        Route::resources([
            'users_dashboard'=>'DashboardController',
            'users_manage'=>'ManageController',
            'users_sessions'=>'SessionController',
            'users_report'=>'ReportController',
            
        ]);
    });
    // for modules
    Route::group(['namespace' => 'Module'], function () {
        Route::resources([
            'module_manage'=>'ManageController',

        ]);
    });
    // for groups
    Route::group(['namespace' => 'Groups'], function () {
        Route::resources([
            'group_manage'=>'ManageController',

        ]);
    });
    // for conference setup
    Route::group(['namespace' => 'VideoConference'], function () {
        Route::resources([
            'conference_manage'=>'ManageController',

        ]);
    });
    // for sms
    Route::group(['namespace' => 'Sms'], function () {
        Route::resources([
            'sms_manage'=>'ManageController',

        ]);
    });
    // for trainees lecturers
    Route::group(['namespace' => 'TraineeLecturer'], function () {
        Route::resources([
            'lecturer_dashboard'=>'DashboardController',
            'lecturer_all_trainees'=>'AllTraineeController',
            'lecturer_course_material'=>'CourseMaterialController',
            'lecturer_attendance'=>'ConferenceAttendanceController',
            'lecturer_exams_result'=>'ResultController',
            
        ]);
    });
    // for trainee moderator
    Route::group(['namespace' => 'TraineeModerator'], function () {
        Route::resources([
            'moderator_dashboard'=>'DashboardController',
            'moderator_setup_course'=>'SetupCourseController',
            'moderator_publish_result'=>'PublishResultController',
            'moderator_video_conference'=>'VideoConferenceController',
            'moderator_manage_trainee'=>'ManageTraineeController',
            'moderator_setup_calendar'=>'SetupCalendarController',
            'moderator_lecturer_assement'=>'ManagelecturerAssementController',
            
        ]);
    });

});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

resources/views/blank.blade.php
@extends('layouts.header')
@section('pageTitle','Blank')
@section('pageBody')
<div class="wrapper">
   <!--Start Page Title-->
   <div class="page-title-box">
      <h4 class="page-title">Blank Page</h4>
      <div class="clearfix"></div>
   </div>
   <!--End Page Title-->          
   <div class="row">
     <div class="col-md-12">
        <div class="white-box">
         <h2 class="header-title">Blank List</h2>
          <hr>
          <div class="table-responsive">
           <table id="" class="tableInit table">
            <thead>
              <th>Name</th>
              <th>Blank</th>
            </thead>
            <tbody>
              <tr>
                <td>Sorce Kwarteng</td>
                <td>
                  <button class="btn btn-primary">Edit <i class="fa fa-edit"></i></button>
                  <button class="btn btn-danger">Delete <i class="fa fa-trash"></i></button>
                </td>
              </tr>
            </tbody>
           </table>  
          </div>
         </div>
     </div>
   </div>
<!-- end  -->
</div>
@endSection

<!-- modal for adding new task -->
type: "POST",
beforeSend:function(){  
    $('#member_save_btn').text("Loading ...").prop("disabled",true); 
},

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
       <!-- CSRF Token -->
      <meta name="csrf-token" content="{{ csrf_token() }}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{{ asset('assets/images/favicon.png') }}" type="image/png">
      <title>GhIS | LSD</title>
      <link href="{{ asset('assets/css/icons.css') }}" rel="stylesheet">
      <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
      <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
      <link href="{{ asset('assets/css/responsive.css') }}" rel="stylesheet">
      <!-- toast -->
      <link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/toastr/toastr.min.css') }}">
   </head>
   <body class="sticky-header">
      <!--Start login Section-->
      <section class="login-section">
         <div class="container">
            <div class="row">
               <div class="login-wrapper">
                  <div class="login-inner">
                     <div class="logo">
                        <img src="{{ asset('assets/images/logo.png') }}"  alt="logo"/>
                     </div>
                     <br>
                     <h2 class="header-title text-center">Login</h2>
                     <form method="GET" action="{{ route('main_dashboard.index') }}"> 
                        @csrf
                        <div class="form-group">
                           <input type="text" class="form-control"  placeholder="Enter Username &hellip;" id="professional_number" name="professional_number" minlength="2"  autofocus  autocomplete="off">
                        </div>
                        <div class="form-group">
                           <input type="password" class="form-control"   id="userPassword" name="userPassword" minlength="3" placeholder="Enter Password &hellip;"  >
                        </div>
                        <div class="form-group">
                           <div class="pull-left">
                              <!-- <div class="checkbox primary">
                                 <input  id="checkbox-2" type="checkbox">
                                 <label for="checkbox-2">Remember me</label>
                              </div> -->
                           </div>
                           <div class="pull-right">
                              <a href="reset-password.html" class="a-link">
                              <i class="fa fa-unlock-alt"></i> Forgot password?
                              </a>
                           </div>
                        </div>
                        <div class="form-group">
                           <input type="hidden" name="mode" id="signInmode" value="login">
                           <button type="submit"  name="submit" id="login"  class="btn btn-primary btn-block">Login <i class="fa fa-sign-in"></i></button>
                        </div>
                        <div class="form-group text-center">
                           Don't have a Trainee account?  <a href="#" style="color: red;">Register </a>
                        </div>
                     </form>
                     <div class="copy-text">
                        <p class="m-0"><?php echo date('Y'); ?> &copy; <a target="_blank" href="http://theprismoid.com/">Prismoidal Company Limited</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!--End login Section-->
      <!--Begin core plugin -->
      <script src="{{ asset('assets/js/jquery.min.js') }}"></script>
      <script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
      <script type="text/javascript" src="{{ asset('assets/plugins/toastr/toastr.min.js') }}"></script>
      <!-- End core plugin -->
      <!-- mcafee antivirus -->
      <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
   </body>
</html>

<script type="text/javascript">
   $("#sigin_Form").on("submit",function(e){
       e.preventDefault();
             $.ajax({
             url:"Controllers/users.php",
             method:"POST",
             data:$("#sigin_Form").serialize(),
             beforeSend:function(){  
                   $('#login').text("Loading ...").prop('disabled',true);  
              },
             success:function(data){  
                 console.log(data);
                  if (data == "success") {
                   toastr.success('Login Successfully');
                   window.location.replace("pages/dashboard.php");
                  }
                  else if(data == "error"){
                   toastr.error('Username or Password Incorrect !');
                   $('#sigin_Form')[0].reset();
                   $('#login').text("LOGIN").prop('disabled',false);
                   $('#signInModal').modal('hide');
                  }
                  else if ((data !="success") || (data !="error")) {
                   var fields = data.split('-');
                   var username = fields[0];
                   var passwd = fields[1];

                   $('#chPassUserName').val(username);
                   $('#chPassUserPassword').val(passwd);
                   $('#signInModal').modal('hide');
                   $('#passChModal').modal('show');
                   $('#professional_number').val("");
                   $('#userPassword').val("");
                   $('#login').text("LOGIN").prop('disabled',false);

                  }
             } 

             });  
   });
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
// Change password 
$("#changePass_form").on("submit",function(e){
    e.preventDefault();
    $.ajax({
    url:"Controllers/users.php",
    method:"POST",
    data:$("#changePass_form").serialize(),
    beforeSend:function(){ 
      $('#resetPass_btn').text("Loading ...").prop("disabled",true); 
          
    },
    success:function(data){ 
    // console.log(data); 
       if (data == "success") {
         toastr.success('Successfully');
         $("#passChModal").modal("hide");
       }
       else if(data == "error"){
       toastr.error('There was an error');
        $('#newPassword').val("");
        $('#newRetypePassword').val("");
        $('#resetPass_btn').text("Reset Password").prop("disabled",false);

       }
    } 

    });  
});

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
</script>

resources/views/regions.blade.php
<option value="Greater_Accra">Greater Accra Region</option>
<option value="Ashanti">Ashanti Region</option>
<option value="Eastern">Eastern Region</option>
<option value="Central">Central Region</option>
<option value="Brong_Ahafo">Brong-Ahafo Region</option>
<option value="Western">Western Region</option>
<option value="Northern">Northern Region</option>
<option value="Upper_East">Upper East Region</option>
<option value="Upper_West">Upper West Region</option>
<option value="Oti_Region">Oti Region Region</option>
<option value="Western_North">Western North Region</option>
<option value="Ahafo">Ahafo Region</option>
<option value="Bono_East">Bono East Region</option>
<option value="Savannah">Savannah Region</option>
<option value="Other">Other</option>