routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// prefix is for route and namespace is for controllers directory
// for guest room
Route::group(['namespace' => 'Guest'], function () {
    Route::resource('cpdGuest', 'RoomDashboardController');
    Route::resource('cpdGuestRoom', 'RoomController');
});
// for login 
Route::get('/', function () {
    return view('auth.login');
});

// for files download
Route::resource('files_download', 'FilesDownloadController');
// for main dashboard
Route::resource('main_dashboard', 'MainDashboardController');


///////////////////// FOR MEMBERS ROUTES //////////////////////////////// 
Route::group(['prefix' => 'Member','namespace' => 'Member'], function () {
    
    // for video conference
    Route::group(['namespace' => 'Conference'], function () {
        Route::resources([
            'conference_dashboard'=>'ConferenceDashboardController',
            'conference_room'=>'ConferenceRoomController',
        ]);
    });
    // for library
    Route::resources([
        'library_dashboard'=>'LibraryController',
        
    ]);
    // for messages
    Route::resources([
        'message_dashboard'=>'MessageController',
        
    ]);
});
// for trainees
Route::group(['prefix' => 'Trainee','namespace' => 'Trainee'], function () {
    Route::resources([
        'dashboard'=>'DashboardController',
        'course_materials'=>'CourseMatController',
        'registration'=>'RegistrationController',
        'fees'=>'FeeController',
        'lecturer_assessment'=>'LecturerAssessController',
        'trainee_conference'=>'ConferenceController',
        'results'=>'ResultController',
        'profile'=>'ProfileController',
    ]);

});

//////////////////////////////////////// FOR ADMIN ////////////////////////////
Route::group(['prefix' => 'Admin','namespace' => 'Admin'], function () {
    // for Members
    Route::group(['namespace' => 'Member'], function () {
        Route::resources([
            'member_dashboard'=>'DashboardController',
            'member_manage'=>'ManageController',
            'member_type'=>'MemberTypeController',
            'member_designation'=>'MemberDesignationController',
            'member_report'=>'ReportController',
            
        ]);
    });
    // for division
    Route::group(['namespace' => 'Division'], function () {
        Route::resources([
            'division_dashboard'=>'DashboardController',
            'division_manage'=>'ManageController',
            'division_account'=>'AccountController',
            'division_report'=>'ReportsController',
            
        ]);
    });
    // for users
    Route::group(['namespace' => 'Users'], function () {
        Route::resources([
            'users_dashboard'=>'DashboardController',
            'users_manage'=>'ManageController',
            'users_sessions'=>'SessionController',
            'users_report'=>'ReportController',
            
        ]);
    });
    // for modules
    Route::group(['namespace' => 'Module'], function () {
        Route::resources([
            'module_manage'=>'ManageController',

        ]);
    });
    // for groups
    Route::group(['namespace' => 'Groups'], function () {
        Route::resources([
            'group_manage'=>'ManageController',

        ]);
    });
    // for conference setup
    Route::group(['namespace' => 'VideoConference'], function () {
        Route::resources([
            'conference_manage'=>'ManageController',

        ]);
    });
    // for sms
    Route::group(['namespace' => 'Sms'], function () {
        Route::resources([
            'sms_manage'=>'ManageController',

        ]);
    });
    // for trainees lecturers
    Route::group(['namespace' => 'TraineeLecturer'], function () {
        Route::resources([
            'lecturer_dashboard'=>'DashboardController',
            'lecturer_all_trainees'=>'AllTraineeController',
            'lecturer_course_material'=>'CourseMaterialController',
            'lecturer_attendance'=>'ConferenceAttendanceController',
            'lecturer_exams_result'=>'ResultController',
            
        ]);
    });
    // for trainee moderator
    Route::group(['namespace' => 'TraineeModerator'], function () {
        Route::resources([
            'moderator_dashboard'=>'DashboardController',
            'moderator_setup_course'=>'SetupCourseController',
            'moderator_publish_result'=>'PublishResultController',
            'moderator_video_conference'=>'VideoConferenceController',
            'moderator_manage_trainee'=>'ManageTraineeController',
            'moderator_setup_calendar'=>'SetupCalendarController',
            'moderator_lecturer_assement'=>'ManagelecturerAssementController',
            
        ]);
    });

});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Module/manageController.php
<?php

namespace App\Http\Controllers\Admin\Module;

use DataTables;
use App\Admin\Module;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class manageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            // get division
            $data = DB::table('modules')->select('modules.id','modules.module_name','modules.module_category','modules.updated_at','divisions.division_alias')
            ->leftJoin('divisions','modules.module_division_id','=','divisions.id')
            ->where('modules.record_hide','NO')->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                        $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editModule">Edit <i class="fa fa-edit"></i></a>';
                        $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteModule">Delete <i class="fa fa-trash"></i></a>';
                        return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }

        // get divisions
        $divisions = DB::table('divisions')->select('id','division_alias')->get();

        return view('admin.module.manage',compact('divisions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = request()->validate([
            'module_division_id' => 'required|numeric',
            'module_name' => 'required|min:3',
            'module_category' => 'required|min:3',
            'module_url' => 'required|min:3'
        ]);
        // after validation add the defaults
        $attributes['updated_member_id'] =1;
        $attributes['record_hide'] ='NO';
        // switch to save or update
        switch ($request->actionType) {
            case 'create':
                // only division that creates can modify
                $attributes['module_division_id'] =1;
                Module::create($attributes);
            break;
            case 'edit':
                Module::findorFail($request->input('module_id'))->update($attributes);
            break;
        }
        
        return response()->json(['message'=>'successful']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $module = Module::find($id);
        return response()->json($module);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // hide record instead of deleting in case is a foreign key in another table
        $attributes['id']= $id;
        $attributes['record_hide']= 'YES';
        $attributes['updated_member_id'] = session()->get('member_id');
        
        Module::findorFail($id)->update($attributes);

        return response()->json(['message'=>'Successful']);
    }
}

resources/views/admin/module/manage.blade.php
@extends('layouts.header')
@section('pageTitle','Manage Modules')
@section('pageBody')

<div class="wrapper">
   <!--Start Page Title-->
   <div class="page-title-box">
      <h4 class="page-title">Manage Modules</h4>
      <div class="clearfix"></div>
   </div>
   <!--End Page Title-->          
   <div class="row">
     <div class="col-md-12">
        <div class="white-box">
         <h2 class="header-title">
            <button class="btn btn-primary" id="addModuleBtn" ><i class="fa fa-plus"></i> Add New </button>
         </h2>
          <hr>
          <div class="table-responsive">
            <table id="table_module" class="table display" style="width:100%">
              <thead class="thead_bg">
                <tr>
                  <th>ID</th>
                  <th>Division</th>
                  <th>Module Name</th>
                  <th>Module Category</th>
                  <th>Last Updated</th>
                  <th>Action</th>
                </tr>
              </thead>
              
            </table>
          </div>
         </div>
     </div>
   </div>
<!-- end  -->
</div>
@endsection

@section('pageScript')
<!-- modal included -->
  @include('admin.module.modal_module')
  <script>
    $(document).ready(function() {
      // inital datatable live
      $('#table_module').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
              url: "{{ route('module_manage.index') }}",
              type: 'GET',
            },
            columns: [
                      { data: 'id', name: 'id', 'visible': false},
                      { data: 'division_alias'},
                      { data: 'module_name'},
                      { data: 'module_category'},
                      { data: 'updated_at'},
                      { data: 'action', orderable: false},
                  ],
            order: [[0, 'desc']]
            
      });
    });
  </script>
@endsection

resources/views/admin/module/modal_module.blade.php
<div  id="addModule" class="modal fade" role="dialog">
   <div class="modal-dialog modal-lg">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close asterick" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="moduleTitle">Add New Module</h4>
         </div>
         
         <form method="POST"  class="form-horizontal" id="module_form">
            <div class="modal-body">
               <!-- modal contnet -->
               <!--  -->
               <div class="row">
                  <div class="col-md-3"><label>Select Division</label> <span class="asterick">*</span></div>
                  <div class="col-md-9">
                     <div class="form-group">
                        <select name="module_division_id" id="module_division_id" class="form-control" required>
                           <option selected disabled>Please Select</option>
                           @foreach($divisions as $division)
                           <option value="{{$division->id}}">{{$division->division_alias}}</option>
                           @endforeach
                        </select>
                     </div>
                  </div>
               </div>
               <!--  -->
               <div class="row">
                  <div class="col-md-3"><label>Module Name</label> <span class="asterick">*</span></div>
                  <div class="col-md-9">
                     <div class="form-group">
                        <input type="text" class="form-control" id="module_name" name="module_name" autocomplete="off" placeholder="Enter Module Name &hellip;" required>
                     </div>
                  </div>
               </div>
               <!--  -->
               <div class="row">
                  <div class="col-md-3"><label>Module Category</label> <span class="asterick">*</span></div>
                  <div class="col-md-9">
                     <div class="form-group">
                        <select name="module_category" id="module_category" class="form-control" required>
                           <option selected disabled>Please Select</option>
                           <option value="Administrator">Administrator</option>
                           <option value="Member">Member</option>
                           <option value="Trainee">Trainee</option>
                        </select>
                     </div>
                  </div>
               </div>
               <!--  -->
               <div class="row">
                  <div class="col-md-3"><label>Module URL</label> <span class="asterick">*</span></div>
                  <div class="col-md-9">
                     <div class="form-group">
                     <textarea name="module_url" id="module_url" rows="20" class="form-control" placeholder="Enter Module URL &hellip;" required> </textarea>
                     </div>
                  </div>
               </div>
               <!--  -->
               <input type="hidden" name="module_id" id="module_id" value="">
               <input type="hidden" name="actionType" id="actionType" value="create">
               <input type="hidden" name="_token" id="csrf-token" value="{{ csrf_token() }}" />
               <!--end modal contnet -->
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
               <button type="button" class="btn btn-primary" id="module_save_btn" >Save <i class="fa fa-save"></i></button>
            </div>
         </form>
      </div>
   </div>
</div>


<script>
    $(document).ready(function() {
      $.ajaxSetup({
         headers: {
               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
         }
      });
      // parsley declaration
      $('#module_form').parsley();
      // on click
      $('#addModuleBtn').click(function () {
          $('#module_form').parsley().reset();
          $('#module_id').val('');
          $('#module_url').html('');
          $('#module_form').trigger("reset");
          $('#moduleTitle').html("Add New Module");
          $('#actionType').val("create");
          $('#module_save_btn').replaceWith('<button type="submit" class="btn btn-primary" id="module_save_btn" value="create">Save <i class="fa fa-save"></i></button>');
          $('#addModule').modal('show');
      });

      // for edit modal
      $('body').on('click', '.editModule', function () {
        $('#module_form').trigger("reset");
        var data_id = $(this).data('id');
        var url = '{{ route("module_manage.edit", ":id") }}';
        url = url.replace(':id', data_id);
        $.get(url, function (data) {
          $('#moduleTitle').html("Edit Module");
          $('#module_id').val(data.id);
          $('#module_name').val(data.module_name);
          $('#module_category').val(data.module_category).trigger('change'); 
          $('#module_division_id').val(data.module_division_id).trigger('change');
          $('#module_url').html(data.module_url);
          $('#actionType').val("edit");
          $('#module_save_btn').replaceWith('<button type="submit" class="btn btn-success" id="module_save_btn" value="edit">Save Changes <i class="fa fa-save"></i></button>');
          $('#addModule').modal('show');
        })
      });

      // for delete
        $(document).on('click', '.deleteModule', function(e){
        e.preventDefault();
        // alert('hello');
        var data_id = $(this).data('id');
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                var data = {
                    "_token": $('input[name=_token]').val(),
                    "id": data_id,
                };
                var url = '{{ route("module_manage.destroy", ":id") }}';
                url = url.replace(':id', data_id);
                $.ajax({
                    type:"delete",
                    url:url,
                    data:data,
                    success: function(response){
                      // console.log(response);
                        swal(response.message, {
                        icon: "success",
                        })
                        .then((willDelete) => {
                          var oTable = $('#table_module').dataTable();
                          oTable.fnDraw(false);
                        }); 
                    },
                });

                
            } 
        });
      });
    
      // for inserting and updating
      $("#module_form").submit(function(e){
        e.preventDefault();
        $.ajax({
          data: $('#module_form').serialize(),
          url: "{{ route('module_manage.store') }}",
          type: "POST",
          success: function (data) {
              switch (data.message) {
                case 'successful':
                  $('#addModule').modal('hide');
                  toastr.success('Process Successfull');
                  var oTable = $('#table_module').dataTable();
                  oTable.fnDraw(false);
                break;
              }
              
          },
          error: function (data) {
              toastr.error('Sorry! error');
              var errormsg = JSON.parse(data.responseText);
              // loop through the 
              swal('Error',errormsg.message,'error')
          }
        });
      });
      
 

  });


  </script>