routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// prefix is for route and namespace is for controllers directory
// for guest room
Route::group(['namespace' => 'Guest'], function () {
    Route::resource('cpdGuest', 'RoomDashboardController');
    Route::resource('cpdGuestRoom', 'RoomController');
});
// for login 
Route::get('/', function () {
    return view('auth.login');
});

// for files download
Route::resource('files_download', 'FilesDownloadController');
// for main dashboard
Route::resource('main_dashboard', 'MainDashboardController');


///////////////////// FOR MEMBERS ROUTES //////////////////////////////// 
Route::group(['prefix' => 'Member','namespace' => 'Member'], function () {
    
    // for video conference
    Route::group(['namespace' => 'Conference'], function () {
        Route::resources([
            'conference_dashboard'=>'ConferenceDashboardController',
            'conference_room'=>'ConferenceRoomController',
        ]);
    });
    // for library
    Route::resources([
        'library_dashboard'=>'LibraryController',
        
    ]);
    // for messages
    Route::resources([
        'message_dashboard'=>'MessageController',
        
    ]);
});
// for trainees
Route::group(['prefix' => 'Trainee','namespace' => 'Trainee'], function () {
    Route::resources([
        'dashboard'=>'DashboardController',
        'course_materials'=>'CourseMatController',
        'registration'=>'RegistrationController',
        'fees'=>'FeeController',
        'lecturer_assessment'=>'LecturerAssessController',
        'trainee_conference'=>'ConferenceController',
        'results'=>'ResultController',
        'profile'=>'ProfileController',
    ]);

});

//////////////////////////////////////// FOR ADMIN ////////////////////////////
Route::group(['prefix' => 'Admin','namespace' => 'Admin'], function () {
    // for Members
    Route::group(['namespace' => 'Member'], function () {
        Route::resources([
            'member_dashboard'=>'DashboardController',
            'member_manage'=>'ManageController',
            'member_type'=>'MemberTypeController',
            'member_designation'=>'MemberDesignationController',
            'member_report'=>'ReportController',
            
        ]);
    });
    // for division
    Route::group(['namespace' => 'Division'], function () {
        Route::resources([
            'division_dashboard'=>'DashboardController',
            'division_manage'=>'ManageController',
            'division_account'=>'AccountController',
            'division_report'=>'ReportsController',
            
        ]);
    });
    // for users
    Route::group(['namespace' => 'Users'], function () {
        Route::resources([
            'users_dashboard'=>'DashboardController',
            'users_manage'=>'ManageController',
            'users_sessions'=>'SessionController',
            'users_report'=>'ReportController',
            
        ]);
    });
    // for modules
    Route::group(['namespace' => 'Module'], function () {
        Route::resources([
            'module_manage'=>'ManageController',

        ]);
    });
    // for groups
    Route::group(['namespace' => 'Groups'], function () {
        Route::resources([
            'group_manage'=>'ManageController',

        ]);
    });
    // for conference setup
    Route::group(['namespace' => 'VideoConference'], function () {
        Route::resources([
            'conference_manage'=>'ManageController',

        ]);
    });
    // for sms
    Route::group(['namespace' => 'Sms'], function () {
        Route::resources([
            'sms_manage'=>'ManageController',

        ]);
    });
    // for trainees lecturers
    Route::group(['namespace' => 'TraineeLecturer'], function () {
        Route::resources([
            'lecturer_dashboard'=>'DashboardController',
            'lecturer_all_trainees'=>'AllTraineeController',
            'lecturer_course_material'=>'CourseMaterialController',
            'lecturer_attendance'=>'ConferenceAttendanceController',
            'lecturer_exams_result'=>'ResultController',
            
        ]);
    });
    // for trainee moderator
    Route::group(['namespace' => 'TraineeModerator'], function () {
        Route::resources([
            'moderator_dashboard'=>'DashboardController',
            'moderator_setup_course'=>'SetupCourseController',
            'moderator_publish_result'=>'PublishResultController',
            'moderator_video_conference'=>'VideoConferenceController',
            'moderator_manage_trainee'=>'ManageTraineeController',
            'moderator_setup_calendar'=>'SetupCalendarController',
            'moderator_lecturer_assement'=>'ManagelecturerAssementController',
            
        ]);
    });

});
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Sms/ManageController.php
<?php

namespace App\Http\Controllers\Admin\Sms;

use DataTables;
use App\Admin\Sms;
use App\Admin\Member;
use App\Admin\MemberType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class ManageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            // get division
            // $data = Sms::latest()->where('division_id',session()->get('member_division_id'))->get();

            $data = DB::table('sms')->select(
                'sms.id',
                'sms.sms_reciever_member_type',
                'sms.sms_reciever_member_id',
                'sms.sms_destination_tel',
                'sms.sms_reference_type',
                'sms.sms_send_message',
                'sms.sms_response',
                'sms.updated_at',
                DB::raw("CONCAT(members.member_first_name,' ',members.member_last_name) AS member_full_name"),
                'member_types.member_type_name'
                )
            ->leftJoin('members','sms.sms_reciever_member_id','=','members.id')
            ->leftJoin('member_types','sms.sms_reciever_member_type','=','member_types.id')
            ->where('sms.division_id',session()->get('member_division_id'))->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                        $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm resendSms"> Resend <i class="fa fa-refresh"></i></a>';
                        return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }

        // for getting division member types
        $memberTypes = MemberType::latest()->where('record_hide','NO')->where('division_id',session()->get('member_division_id'))->get();

        return view('admin.sms.manage',compact('memberTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // request()->validate([
        //     'sms_member_tel' => 'required|integer',
        //     'sms_send_message' => 'required|string|min:3',
        //     'sms_reference_type' => 'required|string|min:3',
        //     'sms_member_type_id' => 'required|string|min:1',
        //     'sms_reciever_member_id' => 'required|integer|min:1',
        // ]);

        if (count($request->all()) >= 1 ) {
            //for sending sms and saving in db
            $smsObj = new Sms;
            // sms group number
            $smsGroupNumber = date('dmY').'-'.mt_rand(1,9100);
            // loop through select and send
            foreach($request->sms_reciever_member_id as $memberId){
                $memberDetails = Member::findorFail($memberId);
                $smsObj->send_sms(
                    $memberDetails->member_tel,
                    $request->sms_send_message,
                    $request->sms_reference_type,
                    $smsGroupNumber,
                    $memberDetails->member_type,
                    $memberId
                );
            }

        }

        // 
        return response()->json(['message'=>'successful']);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //show the members based on all
        switch (trim($id)) {
            case 0:
               $members  = DB::table('members')->select(
                        'members.id','members.member_tel','members.member_type',
                        DB::raw("CONCAT(members.member_first_name,' ',members.member_last_name) AS member_full_name"),
                        'member_types.member_type_name'
                        )
                        ->leftJoin('member_types','member_types.id','=','members.member_type')
                        ->where('members.division_id',session()->get('member_division_id'))->get();
            break;
            default:
                $members  = DB::table('members')->select(
                    'members.id','members.member_tel','members.member_type',
                    DB::raw("CONCAT(members.member_first_name,' ',members.member_last_name) AS member_full_name"),
                    'member_types.member_type_name'
                    )
                    ->leftJoin('member_types','member_types.id','=','members.member_type')
                    ->where('members.member_type',$id)
                    ->where('members.division_id',session()->get('member_division_id'))->get();
            break;
        }

        // loop through and create checkboxes
        foreach($members as $member){
            $data[] = "<tr>
                            <td><input type='checkbox' name='sms_reciever_member_id[]' class='sms_reciever_member_id' value='$member->id' ></td>
                            <td>$member->member_full_name</td>
                            <td>$member->member_type_name</td>
                            <td>$member->member_tel</td>
                        </tr>";
        }
        return response()->json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/sms/manage.blade.php
@extends('layouts.header')
@section('pageTitle','Manage SMS')
@section('pageBody')

<div class="wrapper">
   <!--Start Page Title-->
   <div class="page-title-box">
      <h4 class="page-title">Manage Sms</h4>
      <div class="clearfix"></div>
   </div>
   <!--End Page Title-->          
   <div class="row">
     <div class="col-md-12">
        <div class="white-box">
         <h2 class="header-title">
            <button class="btn btn-primary" id="addSmsBtn" ><i class="fa fa-plus"></i> Add New </button>
         </h2>
          <hr>
          <div class="table-responsive">
            <table id="table_sms" class="table display" style="width:100%">
              <thead class="thead_bg">
                <tr>
                  <th width="10%">Receiver Type</th>
                  <th width="10%">Receiver Name</th>
                  <th width="10%">Receiver Tel</th>
                  <th width="10%">Reference Type</th>
                  <th width="34%">Message Content</th>
                  <th width="10%">Response</th>
                  <th width="10%">Last Updated</th>
                  <th width="10%">Action</th>
                </tr>
              </thead>
              
            </table>
          </div>
         </div>
     </div>
   </div>
<!-- end  -->
</div>
@endsection

@section('pageScript')
<!-- modal included -->
  @include('admin.sms.modal_sms')
  <script>
    $(document).ready(function() {
      // inital datatable live
      $('#table_sms').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
              url: "{{ route('sms_manage.index') }}",
              type: 'GET',
            },
            columns: [
                      { data: 'member_type_name'},
                      { data: 'member_full_name'},
                      { data: 'sms_destination_tel'},
                      { data: 'sms_reference_type'},
                      { data: 'sms_send_message'},
                      { data: 'sms_response'},
                      { data: 'updated_at'},
                      { data: 'action', orderable: false},
                  ],
            order: [[0, 'desc']]
            
      });
    });
  </script>
@endsection

resources/views/admin/sms/modal_sms.blade.php
<div  id="addsms" class="modal fade" role="dialog">
   <div class="modal-dialog modal-xl">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close asterick" data-dismiss="modal">&times;</button>
            <h4 class="modal-title" id="smsTitle">Add New Sms</h4>
         </div>
         <form method="POST" class="form-horizontal" id="sms_form">
            <div class="modal-body">
               <!-- modal contnet -->
               <div class="row">
                  <div class="col-md-7" >
                     <!--  -->
                     <div class="row">
                        <div class="col-md-3"><label>SMS Reference</label> <span class="asterick">*</span></div>
                        <div class="col-md-9">
                           <div class="form-group">
                              <select name="sms_reference_type" id="sms_reference_type" class="form-control" required>
                                 <!-- <option selected disabled>Please Select</option>
                                 <option value="Single">Single Sms</option> -->
                                 <option value="Bulk">Bulk Sms</option>
                              </select>
                           </div>
                        </div>
                     </div>
                     <!--  -->
                     <div class="row">
                        <div class="col-md-3"><label>Member Type</label> <span class="asterick">*</span></div>
                        <div class="col-md-9">
                           <div class="form-group">
                              <select id="sms_reciever_member_type" class="form-control" required>
                                 <option selected disabled>Please Select</option>
                                 <option value="0">All</option>
                                 @foreach($memberTypes as $type)
                                 <option value="{{$type->id}}">{{$type->member_type_name}}</option>
                                 @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                     <!--  -->
                     <hr>
                     <div class="row">
                        <div class="col-md-12">
                           <label>Select Member Receipient</label> <span class="asterick">*</span>
                           <br>
                           <div class="table-responsive">
                              <table class="table table-bordered">
                                 <thead>
                                    <th><input type="checkbox" id="checkAll" ></th>
                                    <th>Member Name</th>
                                    <th>Member Type</th>
                                    <th>Tel Number</th>
                                 </thead>
                                 <tbody id="sms_reciever_member_id_div"></tbody>
                              </table>
                           </div>
                        </div>
   
                     </div>
                  </div>
                  <div class="col-md-5">
                     <!-- for sms counter -->
                     <p><span id="remaining">160 characters remaining</span> <span id="messages" style="color:red;">1 message(s)</span></p>
                     <!--  -->
                     <div class="row m-b-10">
                        <div class="col-md-12">
                           <div class="form-group">
                              <textarea name="sms_send_message" id="sms_send_message" rows="8" class="form-control" required placeholder="Enter Sms Message"> </textarea>
                           </div>
                        </div>
                     </div>
                     
                     <!--  -->
                  </div>
               </div>

               <input type="hidden" name="sms_id" id="sms_id" value="">
               <input type="hidden" name="actionType" id="actionType" value="create">
               <input type="hidden" name="_token" id="csrf-token" value="{{ csrf_token() }}" />
               <!--end modal contnet -->
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
               <button type="submit" class="btn btn-primary" id="sms_save_btn">Save <i class="fa fa-save"></i></button>
            </div>
         </form>
      </div>
   </div>
</div>

<script>
    $(document).ready(function() {
      //  for sms counter
      var $remaining = $('#remaining'),
      $messages = $remaining.next();
      $('#sms_send_message').keyup(function(){
         var chars = this.value.length,
         messages = Math.ceil(chars / 160),
         remaining = messages * 160 - (chars % (messages * 160) || messages * 160);
         $remaining.text(remaining + ' characters remaining');
         $messages.text(messages + ' message(s)');
      });
      // end of sms counter
      //////////////////////////////// 
      $.ajaxSetup({
         headers: {
               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
         }
      });
      // parsley declaration
      $('#sms_form').parsley();

      // for selecting members receivers
      $('#sms_reciever_member_type').on('change', function() {
         var data_id = $('option:selected', this).val();
         var url = '{{ route("sms_manage.show", ":id") }}';
         url = url.replace(':id', data_id);
         $.get(url, function (data) {
            // console.log(data);
            $('#sms_reciever_member_id_div').html(data);
         
        })
      });


      // on click
      $('#addSmsBtn').click(function () {
          $('#sms_form').parsley().reset();
          $('#sms_id').val('');
          $('#sms_form').trigger("reset");
          $('#sms_reciever_member_id_div').html('');
          $('#smsTitle').html("Add New Sms");
          $('#actionType').val("create");
          $('#sms_save_btn').replaceWith('<button type="submit" class="btn btn-primary" id="sms_save_btn">Send SMS <i class="fa fa-send"></i></button>');
          $('#addsms').modal('show');
      });

      // for edit modal
      $('body').on('click', '.editGroup', function () {
        var data_id = $(this).data('id');
        var url = '{{ route("sms_manage.edit", ":id") }}';
        url = url.replace(':id', data_id);
        $.get(url, function (data) {
         //   console.log(data.group_module_id.length);
         $('#smsTitle').html("Edit Group");
         $('#sms_id').val(data.id);
         $('#group_division_id').val(data.group_division_id).trigger('change');
         $('#group_name').val(data.group_name);
         $('.group_module_id').val(data.group_module_id).trigger('change'); 
         $('#actionType').val("edit");
         $('#sms_save_btn').replaceWith('<button type="submit" class="btn btn-primary" id="sms_save_btn">Send SMS <i class="fa fa-send"></i></button>');
         $('#addsms').modal('show');
        })
      });

      // for delete
        $(document).on('click', '.deleteGroup', function(e){
        e.preventDefault();
        // alert('hello');
        var data_id = $(this).data('id');
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((willDelete) => {
            if (willDelete) {
                var data = {
                    "_token": $('input[name=_token]').val(),
                    "id": data_id,
                };
                var url = '{{ route("sms_manage.destroy", ":id") }}';
                url = url.replace(':id', data_id);
                $.ajax({
                    type:"delete",
                    url:url,
                    data:data,
                    success: function(response){
                      console.log(response);
                        swal(response.message, {
                        icon: "success",
                        })
                        .then((willDelete) => {
                          var oTable = $('#table_sms').dataTable();
                          oTable.fnDraw(false);
                        }); 
                    },
                });

                
            } 
        });
      });
    
      // for inserting and updating
      $("#sms_form").submit(function(e){
        e.preventDefault();

        $.ajax({
         data: $('#sms_form').serialize(),
         url: "{{ route('sms_manage.store') }}",
         type: "POST",
         beforeSend:function(){  
            $('#sms_save_btn').text("Loading ...").prop("disabled",true); 
         },
          success: function (data) {
            //  console.log(data);
              switch (data.message) {
                case 'successful':
                  $('#addsms').modal('hide');
                  toastr.success('Process Successfull');
                  var oTable = $('#table_sms').dataTable();
                  oTable.fnDraw(false);
                break;
              }
              
          },
          error: function (data) {
            //  console.log(data.responseText);
              toastr.error('Sorry! error');
              var errormsg = JSON.parse(data.responseText);
              // loop through the 
              swal('Error',errormsg.message,'error')
          }
        });
      });
      
 

  });


  </script>